//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiKiemTra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiKiemTra()
        {
            this.KetQuaKiemTras = new HashSet<KetQuaKiemTra>();
        }
    
        public int id_kiemtra { get; set; }
        public int id_lop { get; set; }
        public System.DateTime ngaykiemtra { get; set; }
        public string LoaiKiemTra { get; set; }
        public decimal max_score { get; set; }
    
        public virtual lophoc lophoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQuaKiemTra> KetQuaKiemTras { get; set; }
    }
}
