//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyhoc
    {
        public int id_dangky { get; set; }
        public int id_hocvien { get; set; }
        public int id_lop { get; set; }
        public System.DateTime ngaydangky { get; set; }
    
        public virtual hocvien hocvien { get; set; }
        public virtual lophoc lophoc { get; set; }
    }
}
