//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQuaKiemTra
    {
        public int id_ketqua { get; set; }
        public int id_kiemtra { get; set; }
        public int id_hocvien { get; set; }
        public decimal diem { get; set; }
        public string remarks { get; set; }
    
        public virtual BaiKiemTra BaiKiemTra { get; set; }
        public virtual hocvien hocvien { get; set; }
    }
}
