//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyTrungTamTiengAnh_AIEntities : DbContext
    {
        public QuanLyTrungTamTiengAnh_AIEntities()
            : base("name=QuanLyTrungTamTiengAnh_AIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiKiemTra> BaiKiemTras { get; set; }
        public virtual DbSet<DangKyhoc> DangKyhocs { get; set; }
        public virtual DbSet<DiemDanh> DiemDanhs { get; set; }
        public virtual DbSet<giaovien> giaoviens { get; set; }
        public virtual DbSet<hocvien> hocviens { get; set; }
        public virtual DbSet<KetQuaKiemTra> KetQuaKiemTras { get; set; }
        public virtual DbSet<khoahoc> khoahocs { get; set; }
        public virtual DbSet<lophoc> lophocs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
